### PR TITLE
PR to add additional CI testing

### PR DESCRIPTION
**Pull request by mmeier93**
## This PR does the following:

- It adds additional CI testing to the pipeline

## Details:

The `ci.yml` file was modified to:
- First have the basic test only using `-profile` (job called `basic_test`) (that test was previously second)
- Then have a second job using matrices of flag options (job called `various_flags_test`). Now has a matrix for both `--gwas_pheno_trait_type` and `--params.effective_population_size`

## Comments:

- There was a small mistake (not actually causing errors) in the previous file version: `nxf_ver: ['20.01.0', '']` was specified in the wrong job (was in the one with extra flags rather than the basic test.
- More tests will be needed:
  - Will need to make some tesdata for testing `--simulate_cb_output` and `--simulate_cb_output_config` (and will need to upload it to S3)
  - Will need to add some extra matrices tests to add to `various_flags_test` job.

## Results:

Latest GitHub actions tests (triggered by push) were successfull.

### CODE REVIEW

**Review by cgpu — APPROVED** [review]
Matrix parameters set up unlocked 🧪, approving!

**Comment by cgpu** [comment]
Out of curiosity, what was the

> syntax error (which was not causing errors)

?

**Comment by mmeier93** [comment]
> Out of curiosity, what was the
> 
> > syntax error (which was not causing errors)
> 
> ?

I just noticed the `gwas_pheno_trait_type: ['binary', 'quantitative']` matrix was present in both the jobs, even though it was only needed in 1. So I removed it in the basic test (now called `basic_test`).

**Comment by mmeier93** [comment]
> Matrix parameters set up unlocked 🧪, approving!

Thanks! 👍

**Pull request merged**
